phrase:
  access_token: 2e7795ddc27754b089eae342c08f7a05ce3ec51de9737afda5ccba77bb33a86a
  project_id: d8b77fd44f98aa3a9793942ac1c66f66
  
  push:
    sources:
    - file: en.json
      params:
        file_format: simple_json
        locale_id: dfafda8948854e6feb81f5f86943fb6a
        update_translations: true 
        
  
  pull:
    targets:
      - file: en.json
        params:
          file_format: simple_json
          locale_id: en
          include_unverified_translations: true
          include_empty_translations: true
     
