phrase:
  access_token: 2e7795ddc27754b089eae342c08f7a05ce3ec51de9737afda5ccba77bb33a86a
  project_id: a2d894203a076ed0172d12bd9be9e24b
  
  push:
    sources:
    - file: en.json
      params:
        file_format: simple_json
        locale_id: 5498358b2c0a648fa8f6744647ef05f0
        update_translations: true 
  
  pull:
    targets:
      - file: it.json
        params:
          file_format: simple_json
          locale_id: ddeda0879b72bccfdb1d3f39c8aaa23a
          
      - file: de.json
        params:
          file_format: simple_json
          locale_id: ea8eeaef2e65a34594c66449b4102bbb
